// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package db

import (
	"context"
)

const createCredential = `-- name: CreateCredential :exec
INSERT INTO user_credentials (user_id, password_hash)
VALUES ($1, $2)
`

type CreateCredentialParams struct {
	UserID       string `json:"user_id"`
	PasswordHash string `json:"password_hash"`
}

// Inserta el hash de una cuenta local. Corre en la MISMA transaccion (pgx) que
// el INSERT en users de register (04 seccion 5.2), para garantizar atomicidad.
func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential, arg.UserID, arg.PasswordHash)
	return err
}

const getPasswordHashByUserID = `-- name: GetPasswordHashByUserID :one
SELECT password_hash
FROM user_credentials
WHERE user_id = $1
`

// Lee el hash para verificar el login (04 seccion 5.3). La ausencia de fila
// (cuenta google, o usuario inexistente) -> domain.ErrInvalidCredential.
func (q *Queries) GetPasswordHashByUserID(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getPasswordHashByUserID, userID)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE user_credentials
SET password_hash = $2,
    updated_at    = now()
WHERE user_id = $1
`

type UpdatePasswordHashParams struct {
	UserID       string `json:"user_id"`
	PasswordHash string `json:"password_hash"`
}

// Actualiza el hash (cambio de contrasena). La aplicacion fija updated_at.
func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.UserID, arg.PasswordHash)
	return err
}
