// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"time"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    id, user_id, event_type, contact_name, contact_ref,
    location_lat, location_lng, location_label, description,
    starts_at, event_status, reminder_type, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, user_id, event_type, contact_name, contact_ref, location_lat, location_lng, location_label, description, starts_at, event_status, reminder_type, created_at, updated_at
`

type CreateEventParams struct {
	ID            string    `json:"id"`
	UserID        string    `json:"user_id"`
	EventType     string    `json:"event_type"`
	ContactName   string    `json:"contact_name"`
	ContactRef    string    `json:"contact_ref"`
	LocationLat   float64   `json:"location_lat"`
	LocationLng   float64   `json:"location_lng"`
	LocationLabel string    `json:"location_label"`
	Description   string    `json:"description"`
	StartsAt      time.Time `json:"starts_at"`
	EventStatus   string    `json:"event_status"`
	ReminderType  string    `json:"reminder_type"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// El id, created_at y updated_at los provee la aplicacion (sellado app-layer).
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.UserID,
		arg.EventType,
		arg.ContactName,
		arg.ContactRef,
		arg.LocationLat,
		arg.LocationLng,
		arg.LocationLabel,
		arg.Description,
		arg.StartsAt,
		arg.EventStatus,
		arg.ReminderType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.ContactName,
		&i.ContactRef,
		&i.LocationLat,
		&i.LocationLng,
		&i.LocationLabel,
		&i.Description,
		&i.StartsAt,
		&i.EventStatus,
		&i.ReminderType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :execrows
DELETE FROM events
WHERE id = $1 AND user_id = $2
`

type DeleteEventParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

// Devuelve filas afectadas: 0 -> ErrEventNotFound.
func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEvent, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, user_id, event_type, contact_name, contact_ref, location_lat, location_lng, location_label, description, starts_at, event_status, reminder_type, created_at, updated_at FROM events
WHERE id = $1 AND user_id = $2
`

type GetEventByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

// Scoping estructural por user_id: 0 filas -> ErrEventNotFound (no filtra ajeno).
func (q *Queries) GetEventByID(ctx context.Context, arg GetEventByIDParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, arg.ID, arg.UserID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.ContactName,
		&i.ContactRef,
		&i.LocationLat,
		&i.LocationLng,
		&i.LocationLabel,
		&i.Description,
		&i.StartsAt,
		&i.EventStatus,
		&i.ReminderType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET event_type     = $3,
    contact_name   = $4,
    contact_ref    = $5,
    location_lat   = $6,
    location_lng   = $7,
    location_label = $8,
    description    = $9,
    starts_at      = $10,
    event_status   = $11,
    reminder_type  = $12,
    updated_at     = $13
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, event_type, contact_name, contact_ref, location_lat, location_lng, location_label, description, starts_at, event_status, reminder_type, created_at, updated_at
`

type UpdateEventParams struct {
	ID            string    `json:"id"`
	UserID        string    `json:"user_id"`
	EventType     string    `json:"event_type"`
	ContactName   string    `json:"contact_name"`
	ContactRef    string    `json:"contact_ref"`
	LocationLat   float64   `json:"location_lat"`
	LocationLng   float64   `json:"location_lng"`
	LocationLabel string    `json:"location_label"`
	Description   string    `json:"description"`
	StartsAt      time.Time `json:"starts_at"`
	EventStatus   string    `json:"event_status"`
	ReminderType  string    `json:"reminder_type"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// updated_at lo re-sella la aplicacion (05 seccion 4.1). Scoping por user_id.
func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.UserID,
		arg.EventType,
		arg.ContactName,
		arg.ContactRef,
		arg.LocationLat,
		arg.LocationLng,
		arg.LocationLabel,
		arg.Description,
		arg.StartsAt,
		arg.EventStatus,
		arg.ReminderType,
		arg.UpdatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.ContactName,
		&i.ContactRef,
		&i.LocationLat,
		&i.LocationLng,
		&i.LocationLabel,
		&i.Description,
		&i.StartsAt,
		&i.EventStatus,
		&i.ReminderType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
