// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerificationToken struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type Event struct {
	ID            string    `json:"id"`
	UserID        string    `json:"user_id"`
	EventType     string    `json:"event_type"`
	ContactName   string    `json:"contact_name"`
	ContactRef    string    `json:"contact_ref"`
	LocationLat   float64   `json:"location_lat"`
	LocationLng   float64   `json:"location_lng"`
	LocationLabel string    `json:"location_label"`
	Description   string    `json:"description"`
	StartsAt      time.Time `json:"starts_at"`
	EventStatus   string    `json:"event_status"`
	ReminderType  string    `json:"reminder_type"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type User struct {
	ID            string    `json:"id"`
	Email         string    `json:"email"`
	Nombre        string    `json:"nombre"`
	AuthProvider  string    `json:"auth_provider"`
	CreatedAt     time.Time `json:"created_at"`
	GoogleSub     *string   `json:"google_sub"`
	EmailVerified bool      `json:"email_verified"`
}

type UserCredential struct {
	UserID       string    `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
