// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Desvincula Google de la cuenta (google_sub = NULL). 0 filas -> ErrUserNotFound.
	ClearGoogleSub(ctx context.Context, id string) (int64, error)
	// Inserta el hash de una cuenta local. Corre en la MISMA transaccion (pgx) que
	// el INSERT en users de register (04 seccion 5.2), para garantizar atomicidad.
	CreateCredential(ctx context.Context, arg CreateCredentialParams) error
	// El id, created_at y updated_at los provee la aplicacion (sellado app-layer).
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	// id y created_at los provee la aplicacion. google_sub es NULL salvo en cuentas
	// nacidas de Google (se sella con el sub del idToken). Una violacion de
	// users_email_lower_uniq se traduce en ErrEmailTaken.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Devuelve filas afectadas: 0 -> ErrEventNotFound.
	DeleteEvent(ctx context.Context, arg DeleteEventParams) (int64, error)
	// Borra la cuenta. events y user_credentials referencian users con ON DELETE
	// CASCADE, asi que esta unica sentencia elimina tambien todos los datos del
	// usuario. Devuelve las filas afectadas: 0 -> ErrUserNotFound.
	DeleteUser(ctx context.Context, id string) (int64, error)
	// Scoping estructural por user_id: 0 filas -> ErrEventNotFound (no filtra ajeno).
	GetEventByID(ctx context.Context, arg GetEventByIDParams) (Event, error)
	// Lee el hash para verificar el login (04 seccion 5.3). La ausencia de fila
	// (cuenta google, o usuario inexistente) -> domain.ErrInvalidCredential.
	GetPasswordHashByUserID(ctx context.Context, userID string) (string, error)
	// Lookup case-insensitive via el indice funcional users_email_lower_uniq.
	// 0 filas -> ErrUserNotFound.
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	// Lookup por el sub inmutable de Google (la llave de vinculacion, no el email).
	// 0 filas -> ErrUserNotFound.
	GetUserByGoogleSub(ctx context.Context, googleSub *string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	// Adjunta el sub de Google a la cuenta. Una violacion de unicidad (el sub ya
	// esta en otra cuenta) la traduce el repo a ErrGoogleLinkConflict.
	// 0 filas -> ErrUserNotFound.
	LinkGoogleSub(ctx context.Context, arg LinkGoogleSubParams) (int64, error)
	// updated_at lo re-sella la aplicacion (05 seccion 4.1). Scoping por user_id.
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	// Actualiza el hash (cambio de contrasena). La aplicacion fija updated_at.
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
}

var _ Querier = (*Queries)(nil)
