// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Inserta el hash de una cuenta local. Corre en la MISMA transaccion (pgx) que
	// el INSERT en users de register (04 seccion 5.2), para garantizar atomicidad.
	CreateCredential(ctx context.Context, arg CreateCredentialParams) error
	// El id, created_at y updated_at los provee la aplicacion (sellado app-layer).
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	// id y created_at los provee la aplicacion. Una violacion de
	// users_email_lower_uniq se traduce en ErrEmailTaken.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Devuelve filas afectadas: 0 -> ErrEventNotFound.
	DeleteEvent(ctx context.Context, arg DeleteEventParams) (int64, error)
	// Scoping estructural por user_id: 0 filas -> ErrEventNotFound (no filtra ajeno).
	GetEventByID(ctx context.Context, arg GetEventByIDParams) (Event, error)
	// Lee el hash para verificar el login (04 seccion 5.3). La ausencia de fila
	// (cuenta google, o usuario inexistente) -> domain.ErrInvalidCredential.
	GetPasswordHashByUserID(ctx context.Context, userID string) (string, error)
	// Lookup case-insensitive via el indice funcional users_email_lower_uniq.
	// 0 filas -> ErrUserNotFound.
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	// updated_at lo re-sella la aplicacion (05 seccion 4.1). Scoping por user_id.
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	// Actualiza el hash (cambio de contrasena). La aplicacion fija updated_at.
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
}

var _ Querier = (*Queries)(nil)
