// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, nombre, auth_provider, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, nombre, auth_provider, created_at
`

type CreateUserParams struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	Nombre       string    `json:"nombre"`
	AuthProvider string    `json:"auth_provider"`
	CreatedAt    time.Time `json:"created_at"`
}

// id y created_at los provee la aplicacion. Una violacion de
// users_email_lower_uniq se traduce en ErrEmailTaken.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Nombre,
		arg.AuthProvider,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nombre,
		&i.AuthProvider,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, nombre, auth_provider, created_at FROM users
WHERE lower(email) = lower($1)
`

// Lookup case-insensitive via el indice funcional users_email_lower_uniq.
// 0 filas -> ErrUserNotFound.
func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nombre,
		&i.AuthProvider,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, nombre, auth_provider, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nombre,
		&i.AuthProvider,
		&i.CreatedAt,
	)
	return i, err
}
