// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"
)

const clearGoogleSub = `-- name: ClearGoogleSub :execrows
UPDATE users SET google_sub = NULL
WHERE id = $1
`

// Desvincula Google de la cuenta (google_sub = NULL). 0 filas -> ErrUserNotFound.
func (q *Queries) ClearGoogleSub(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, clearGoogleSub, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, nombre, auth_provider, google_sub, email_verified, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, nombre, auth_provider, created_at, google_sub, email_verified
`

type CreateUserParams struct {
	ID            string    `json:"id"`
	Email         string    `json:"email"`
	Nombre        string    `json:"nombre"`
	AuthProvider  string    `json:"auth_provider"`
	GoogleSub     *string   `json:"google_sub"`
	EmailVerified bool      `json:"email_verified"`
	CreatedAt     time.Time `json:"created_at"`
}

// id y created_at los provee la aplicacion. google_sub es NULL salvo en cuentas
// nacidas de Google (se sella con el sub del idToken). email_verified lo decide
// la aplicacion: true para cuentas de origen Google (el idToken ya dio fe del
// correo), false para registro por contrasena. Una violacion de
// users_email_lower_uniq se traduce en ErrEmailTaken.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Nombre,
		arg.AuthProvider,
		arg.GoogleSub,
		arg.EmailVerified,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nombre,
		&i.AuthProvider,
		&i.CreatedAt,
		&i.GoogleSub,
		&i.EmailVerified,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users
WHERE id = $1
`

// Borra la cuenta. events y user_credentials referencian users con ON DELETE
// CASCADE, asi que esta unica sentencia elimina tambien todos los datos del
// usuario. Devuelve las filas afectadas: 0 -> ErrUserNotFound.
func (q *Queries) DeleteUser(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, nombre, auth_provider, created_at, google_sub, email_verified FROM users
WHERE lower(email) = lower($1)
`

// Lookup case-insensitive via el indice funcional users_email_lower_uniq.
// 0 filas -> ErrUserNotFound.
func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nombre,
		&i.AuthProvider,
		&i.CreatedAt,
		&i.GoogleSub,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, email, nombre, auth_provider, created_at, google_sub, email_verified FROM users
WHERE google_sub = $1
`

// Lookup por el sub inmutable de Google (la llave de vinculacion, no el email).
// 0 filas -> ErrUserNotFound.
func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nombre,
		&i.AuthProvider,
		&i.CreatedAt,
		&i.GoogleSub,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, nombre, auth_provider, created_at, google_sub, email_verified FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nombre,
		&i.AuthProvider,
		&i.CreatedAt,
		&i.GoogleSub,
		&i.EmailVerified,
	)
	return i, err
}

const linkGoogleSub = `-- name: LinkGoogleSub :execrows
UPDATE users SET google_sub = $2
WHERE id = $1
`

type LinkGoogleSubParams struct {
	ID        string  `json:"id"`
	GoogleSub *string `json:"google_sub"`
}

// Adjunta el sub de Google a la cuenta. Una violacion de unicidad (el sub ya
// esta en otra cuenta) la traduce el repo a ErrGoogleLinkConflict.
// 0 filas -> ErrUserNotFound.
func (q *Queries) LinkGoogleSub(ctx context.Context, arg LinkGoogleSubParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkGoogleSub, arg.ID, arg.GoogleSub)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEmailVerified = `-- name: SetEmailVerified :execrows
UPDATE users SET email_verified = true
WHERE id = $1
`

// Marca el correo del usuario como verificado (gate suave; idempotente). 0 filas
// -> ErrUserNotFound.
func (q *Queries) SetEmailVerified(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, setEmailVerified, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
