// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerificationToken = `-- name: CreateVerificationToken :exec
INSERT INTO email_verification_tokens (id, user_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateVerificationTokenParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

// id, token_hash, expires_at y created_at los provee la aplicacion. Solo se
// guarda el hash; el token crudo viaja en el correo y no se persiste.
func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, createVerificationToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const getVerificationTokenByHash = `-- name: GetVerificationTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM email_verification_tokens
WHERE token_hash = $1
`

// Busca por el hash del token presentado. 0 filas -> ErrInvalidVerificationToken.
func (q *Queries) GetVerificationTokenByHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getVerificationTokenByHash, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markVerificationTokenUsed = `-- name: MarkVerificationTokenUsed :execrows
UPDATE email_verification_tokens SET used_at = $2
WHERE id = $1 AND used_at IS NULL
`

type MarkVerificationTokenUsedParams struct {
	ID     string             `json:"id"`
	UsedAt pgtype.Timestamptz `json:"used_at"`
}

// Marca el token como usado de forma atomica y de UN SOLO USO: la condicion
// used_at IS NULL hace que dos confirmaciones concurrentes solo una afecte filas
// (la otra ve 0 filas -> token ya usado). 0 filas -> ya usado (o id inexistente).
func (q *Queries) MarkVerificationTokenUsed(ctx context.Context, arg MarkVerificationTokenUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markVerificationTokenUsed, arg.ID, arg.UsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
